steps:  
  - task: NodeTool@0
    inputs:
      versionSpec: 10.16.0
    condition: and(succeeded(), eq(variables.updated, 'true'))
  - task: Npm@1
    displayName: Install npm package
    inputs:
      command: install
      workingDir: src/crm.portal.web
    condition: and(succeeded(), eq(variables.updated, 'true'))
  - task: Npm@1
    displayName: Build CRM portal web
    inputs:
      command: custom
      workingDir: src/crm.portal.web
      customCommand: run build        
    condition: and(succeeded(), eq(variables.updated, 'true'))
  - script: |
      docker build -t crm-portal-web:latest .
    workingDirectory: src/crm.portal.web
    condition: and(succeeded(), eq(variables.updated, 'true'))
