jobs:
  - job: Setup_Gitflow
    displayName: Setup Gitflow
    pool:
      name: Azure Pipelines
      vmImage: windows-latest
    steps:
      - task: gep13.chocolatey-azuredevops.chocolatey-azuredevops.ChocolateyCommand@0
        displayName: 'Chocolatey install'
        inputs:
          command: install
          installPackageId: GitVersion.Portable

      - powershell: |         
          GitVersion.exe /output buildserver /nofetch          
        displayName: 'PowerShell Script'