version: "3.7"

services:

  # nats:
  #   ports:
  #     - 4222:4222
  #     - 6222:6222
  #     - 8222:8222

  communication-api-test:
    environment:
      - NATS__Url=http://nats:4222
    entrypoint:
      - dotnet
      - test
      - --logger
      - trx;LogFileName=${COMMON_TESTRESULTSDIRECTORY}/communication-api-test/test-results.trx
      - /p:CollectCoverage=true
      - /p:CoverletOutputFormat=opencover
      - /p:CoverletOutput=${COMMON_TESTRESULTSDIRECTORY}/communication-api-test/coverage/
      - --no-restore

  contact-api-test:
    environment:
      - NATS__Url=http://nats:4222
      - ConnectionStrings__default=Server=postgresql;Port=5432;Database=crm-contact;User Id=lab;Password=P@ssw0rd;
    entrypoint:
      - dotnet
      - test
      - --logger
      - trx;LogFileName=${COMMON_TESTRESULTSDIRECTORY}/contact-api-test/test-results.trx
      - /p:CollectCoverage=true
      - /p:CoverletOutputFormat=opencover
      - /p:CoverletOutput=${COMMON_TESTRESULTSDIRECTORY}/contact-api-test/coverage/
      - --no-restore
