version: '3.7'

services:
  vault:
    ports: 
      - 8200:8200
    environment: 
      - VAULT_DEV_ROOT_TOKEN_ID=secret

  postgres.data:
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=lab
      - POSTGRES_PASSWORD=P@ssw0rd

  keycloak:
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_USER=lab
      - KEYCLOAK_PASSWORD=P@ssw0rd
      - DB_ADDR=postgres.data
      - DB_USER=lab
      - DB_PASSWORD=P@ssw0rd
      - PROXY_ADDRESS_FORWARDING=true
      - DB_VENDOR=postgres
      - DB_DATABASE=keycloak

  crmportal.web:
    ports:
      - 5000:80

