version: '3.7'

services:

  postgres.data:
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=lab
      - POSTGRES_PASSWORD=P@ssw0rd

  keycloak:
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_USER=lab
      - KEYCLOAK_PASSWORD=P@ssw0rd
      - DB_ADDR=postgres.data
      - DB_USER=lab
      - DB_PASSWORD=P@ssw0rd

  crmportal.web:
    ports:
      - 5000:80

