version: "3.7"

services:

  nats:
    image: nats

  postgresql:
    image: postgres:11-alpine

  communication-api-test:
    image: crmnow/communication-api-test:latest
    build:
      context: .
      dockerfile: src/Communication/CRM.Communication/Dockerfile
      target: functionaltest
      args:
        - feed=${NUGET_FEED:- --source "https://api.nuget.org/v3/index.json"}
    depends_on:
      - nats
    volumes:
      - azp-data:/azp

  contact-api-test:
    image: crmnow/contact-api-test:latest
    build:
      context: .
      dockerfile: src/Contact/CRM.Contact/Dockerfile
      target: functionaltest
      args:
        - feed=${NUGET_FEED:- --source "https://api.nuget.org/v3/index.json"}
    depends_on:
      - nats
      - postgresql
    volumes:
      - azp-data:/azp

volumes:
  azp-data:
    name: azp-data
    external: true
