---
- hosts: all
  connection: local
  gather_facts: false
  become: true
#   become_method: sudo
#   become_user: root
#   become_flags: '-s /bin/bash'
  vars:
    ansible_python_interpreter: /usr/bin/python3
    
  tasks:
    # - ping:

    - debug:
        # msg: >
        #     "{% if azure.enable_public_ip == true %}
        #         'ssss'
        #     {% else %}
        #         'sssgggg'
        #     {% endif %}"

        msg: "{{ 'ansible_distribution_release' if(azure.enable_public_ip == true)  else 'ddd' }}"


    # - apt:
    #     update_cache: yes
        
    # - apt:
    #     state: latest 
    #     update_cache: yes
    #     pkg:
    #         - apt-transport-https
    #         - ca-certificates
    #         - curl
    #         - gnupg-agent
    #         - software-properties-common
    
    # - name: Add Docker GPG apt Key
    #   apt_key:
    #     url: https://download.docker.com/linux/ubuntu/gpg
    #     state: present

  
    # - name: Add Docker Repository
    #   apt_repository:
    #     repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable
    #     state: present

    # - name: Update apt and install docker-ce
    #   apt: update_cache=yes name=docker-ce state=latest

    # - name: Install Docker Module for Python
    #   pip:
    #     name: docker
    # - apt:
    #     update_cache: yes
        # become: yes
    # - include_role:
    #     name: docker