---
- hosts: localhost
  connection: local
  vars:
    resource_group: lab01
    vm_name: vm01
    location: eastasia
    ssh_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDUaLxTO5KocbEeQc/athgHpLOUpFvYR0AvQf2Yzp4SI8WuMJBgTIoDlfWRO7royj/Vsa8i34TeQbH+WqoIYpppsyu2gmBd/Eigb4w1o6iRswUuxFt3n1jr8aNbytpJ8VdSyq8z8GlUvSzQl4j8jPvZUg9HkQB+qBwaC+rFdIff+8Vq6lFdclUOoNFpJf2Q5l4iiB0fu6w9OoHjkqTx8bWAB5IXvxlw2cxMYhxDE7pyDaaHwT6QitQBQWlLHVRmuoSnrdykdoKIhH9WkBdX19Kdc/HJywjzKCzTYnRADbJC1+pYVjMMj09ZrZ78rOm5VekvcTSOHKud4kXSh5UU3ZS7 phuongle@Phuongs-MacBook-Pro.local"
  tasks:
    - name: Create resouce group
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"
    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: "{{ resource_group }}"
        name: lab-vpn
        address_prefixes: "172.10.0.0/16"
    - name: Add subnet
      azure_rm_subnet:
        resource_group: "{{ resource_group }}"
        name: "vm-subnet"
        address_prefix: "172.10.2.0/24"
        virtual_network: "lab-vpn"

    - name: Create virtual network inteface card
      azure_rm_networkinterface:
        resource_group: "{{ resource_group }}"
        name: "nic-{{ vm_name }}"
        virtual_network: "lab-vpn"
        subnet: "vm-subnet"
        ip_configurations:
          - name: ipconfig1
            primary: true
      register: foo_result
    
    # - name: Get simple value
    #   set_fact:
    #     simple_value: "{{ (foo_result.stdout | from_json) }}"

    - debug:
        msg: "{{ foo_result.state }}"

    - name: Create VM
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}"
        vm_size: Standard_B1s
        admin_username: azureuser
        ssh_password_enabled: false
        ssh_public_keys:
          - path: /home/azureuser/.ssh/authorized_keys
            key_data: "{{ ssh_key }}"
        network_interfaces: "nic-{{ vm_name }}"
        image:
          offer: UbuntuServer
          publisher: Canonical
          sku: 16.04-LTS
          version: latest

