parameters:
  componentName: ''
  subPath: ''
  componentTemplate: ''  

jobs:  
  - job: ${{ format('Check_changes_for_{0}', parameters.componentName) }}
    displayName: ${{ format('Check changes for {0}', parameters.componentName) }}    
    steps:
      - template: check-update-status.yml        
        parameters:
          componentName: ${{ parameters.componentName }}
          subPath: ${{ parameters.subPath }}
    
      - template: ${{ format('{0}/{1}', variables.Build.SourcesDirectory, parameters.componentTemplate) }}    
