parameters:
  componentName: ''
  subPath: ''
  componentTemplate: ''

jobs:
  - job: ${{ format('build_{0}', parameters.componentName) }}
    displayName: ${{ format('Build {0}', parameters.componentName) }}
    pool:
      name: default
    steps:
      - checkout: self
        persistCredentials: "true"
      - template: check-update-status.yml
        parameters:
          componentName: ${{ parameters.componentName }}
          subPath: ${{ parameters.subPath }}      
      - template: ${{ format('{0}/{1}', variables.Build.SourcesDirectory, parameters.componentTemplate) }}