# Default values for communication-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: crmnow/communication-api
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "communication-api"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

env:
  values:
    - name: rabbitMQ__Url
      value: rabbitmq://rabbitmq
    - name: Jaeger__UdpHost
      value: jaeger-agent.monitoring.svc.cluster.local
    - name: Logging__Seq__ApiKey
      value: t49Qq9hx0JrfnKXwK5UZ
    - name: Logging__Seq__Url
      value: http://seq.monitoring.svc.cluster.local
