---

- name: Install packages to allow apt to use a repository over HTTPS
  apt:
    state: latest
    update_cache: yes
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

- name: Install docker python package 
  pip:
    name: docker-py

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Update repositories cache
  apt:
    update_cache: yes

- name: Install docker packages
  apt:
    state: latest
    update_cache: yes
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Pull default Docker image
  docker_image:
    name: 'hello-world'
    source: pull
