trigger:
  branches:
    include:
      - master
      - feature/*
    exclude:
      - ref/tags/*

jobs:
  - template: templates/build-component.job.yml
    parameters:
      componentName: crmPortalWeb
      subPath: src/crm.portal.web
      componentTemplate: src/crm.portal.web/build.yml
  - template: templates/build-component.job.yml
    parameters:
      componentName: crmCustomerAPI
      subPath: src/crm.customer.api
      componentTemplate: src/crm.customer.api/build.yml
