parameters:
  services: ''

jobs:
  - job: Build_service
    displayName: Build services
    dependsOn: Prepare_environment
    variables:
      CRM.ShortCommit: $[dependencies.Prepare_environment.outputs['setGlobalVarStep.CRM.ShortCommit']]
    pool:
      name: default
    steps:
      - task: Bash@3
        displayName: Environment variables
        inputs:
          targetType: inline
          script: |
            echo ${{ parameters.shortCommit }}
            
      - task: DockerCompose@0
        displayName: Compose build ${{ parameters.services }}
        inputs:
          dockerComposeCommand: 'build ${{ parameters.services }}'
          containerregistrytype: Container Registry
          dockerComposeFile: docker-compose.yml
          qualifyImageNames: true
          projectName: ''
          dockerComposeFileArgs: |
            TAG=$(CRM.ShortCommit)