trigger:
  branches:
    include:
      - master
      - feature/*
    exclude:
      - ref/tags/*
  paths:
    include:
      - src/crm.portal.web

stages:
  - stage: Build    
    jobs:
      - job: checkout_code
        displayName: Checkout source code
        steps:          
        - checkout: self
          persistCredentials: "true"
          
      - template: templates/build-component.job.yml
        parameters:
          componentName: crmPortalWeb
          subPath: src/crm.portal.web
          componentTemplate: src/crm.portal.web/build.yml          
  
  - stage: Deploy_Dev_Env  
    displayName: Deploy Dev Env
    jobs:
    - deployment: DeployCRM_portal_web
      environment: dev-env
      strategy:
        runOnce:
          deploy:
            steps:
            - script: |
                docker version
                docker rm --force crm-portal-web
                docker run -d --name crm-portal-web --net lab-network --restart unless-stopped crm-portal-web:latest
