trigger:
  branches:
    include:
      - master
      - feature/*
    exclude:
      - ref/tags/*
  paths:
    include:
      - src/crm.customer.api

stages:
  - stage: Build
    jobs:
    - template: templates/build-component.job.yml
      parameters:
        componentName: crmCustomerAPI
        subPath: src/crm.customer.api
        componentTemplate: src/crm.customer.api/build.yml
        
  - stage: Deploy_Dev_Env  
    displayName: Deploy Dev Env
    jobs:
    - deployment: DeployCRM_portal_web
      environment: dev-env
      strategy:
        runOnce:
          deploy:
            steps:
            - script: |
                docker version
