parameters:
  service: ''
  azuresubscription: ''
  azureresourcegroup: ''
  kubernetescluster: ''
  kubernetesnamespace: ''

jobs:
  - deployment: Install_Helm_Chart
    displayName: Install helm chart
    variables:
      crm.shortcommit: $[dependencies.Prepare_environment.outputs['setGlobalVarStep.crm.shortcommit']]
      crm.helmversion: $[dependencies.Prepare_environment.outputs['setGlobalVarStep.crm.helmversion']]
      crm.kubectlversion: $[dependencies.Prepare_environment.outputs['setGlobalVarStep.crm.kubectlversion']]
    dependsOn: 
    - Prepare_environment
    pool:
      name: default
    environment: ${{ parameters.kubernetesnamespace }}
    strategy:
      runOnce:
        deploy:
          steps:
            - task: HelmInstaller@0
              displayName: Helm installer
              inputs:
                helmVersion: $(crm.helmversion)
                kubectlVersion: $(crm.kubectlversion)
                checkLatestKubectl: false
                
            - task: HelmDeploy@0
              displayName: Helm version
              inputs:
                azureSubscription: ${{ parameters.azuresubscription }}
                azureResourceGroup: ${{ parameters.azureresourcegroup }}
                kubernetesCluster: ${{ parameters.kubernetescluster }}
                command: version

            - task: HelmDeploy@0
              displayName: Helm install
              inputs:
                azureSubscription: ${{ parameters.azuresubscription }}
                azureResourceGroup: ${{ parameters.azureresourcegroup }}
                kubernetesCluster: ${{ parameters.kubernetescluster }}
                namespace: ${{ parameters.kubernetesnamespace }}
                releaseName: ${{ parameters.service }}-${{ parameters.kubernetesnamespace }}
                command: upgrade
                chartType: FilePath
                chartPath: $(Pipeline.Workspace)/helm/${{ parameters.service }}-$(Build.BuildNumber).tgz
                arguments: --install