parameters:
  service: ''
  kubernetesnamespace: ''
  azuresubscription: ''
  azureresourcegroup: ''
  kubernetescluster: ''

jobs:
  - deployment: Install_Helm_Chart
    displayName: Install helm chart
    variables:
      shortcommit: $[dependencies.Prepare_environment.outputs['setGlobalVarStep.shortcommit']]
      helmversion: $[dependencies.Prepare_environment.outputs['setGlobalVarStep.helmversion']]
      kubectlversion: $[dependencies.Prepare_environment.outputs['setGlobalVarStep.kubectlversion']]
    dependsOn: 
    - Prepare_environment
    pool:
      name: default
    environment: ${{ parameters.kubernetesnamespace }}
    strategy:
      runOnce:
        deploy:
          steps:
            - task: HelmInstaller@0
              displayName: Helm installer
              inputs:
                helmVersion: $(helmversion)
                kubectlVersion: $(kubectlversion)
                checkLatestKubectl: false
                
            - task: HelmDeploy@0
              displayName: Helm version
              inputs:
                azureSubscription: $(azuresubscription)
                azureResourceGroup: $(azureresourcegroup)
                kubernetesCluster: $(kubernetescluster)
                command: version

            - task: HelmDeploy@0
              displayName: Helm install
              inputs:
                azureSubscription: $(azuresubscription)
                azureResourceGroup: $(azureresourcegroup)
                kubernetesCluster: $(kubernetescluster)
                namespace: ${{ parameters.kubernetesnamespace }}
                releaseName: ${{ parameters.service }}-${{ parameters.kubernetesnamespace }}
                command: upgrade
                chartType: FilePath
                chartPath: $(Pipeline.Workspace)/helm/${{ parameters.service }}-$(Build.BuildNumber).tgz
                install: true
                overrideValues: image.tag=$(shortcommit)