parameters:
  name: 'Install_Helm_Chart'
  chartname: ''
  releasename: ''
  kubernetesnamespace: ''
  azuresubscription: ''
  azureresourcegroup: ''
  kubernetescluster: ''
  valueFile: ''

jobs:
  - deployment: ${{ parameters.name }}
    displayName: Install helm chart - ${{ parameters.releasename }}
    variables:
      shortcommit: $[dependencies.Prepare_environment.outputs['setGlobalVarStep.shortcommit']]
      helmversion: $[dependencies.Prepare_environment.outputs['setGlobalVarStep.helmversion']]
      kubectlversion: $[dependencies.Prepare_environment.outputs['setGlobalVarStep.kubectlversion']]
    dependsOn: 
    - Prepare_environment
    pool:
      name: default
    environment: ${{ parameters.kubernetesnamespace }}
    strategy:
      runOnce:
        deploy:
          steps:
            - task: HelmInstaller@0
              displayName: Helm installer
              inputs:
                helmVersion: $(helmversion)
                kubectlVersion: $(kubectlversion)
                checkLatestKubectl: false
                
            - task: HelmDeploy@0
              displayName: Helm version
              inputs:
                azureSubscription: ${{ parameters.azuresubscription }}
                azureResourceGroup: ${{ parameters.azureresourcegroup }}
                kubernetesCluster: ${{ parameters.kubernetescluster }}
                command: version

            - task: HelmDeploy@0
              displayName: Helm install
              inputs:
                azureSubscription: ${{ parameters.azuresubscription }}
                azureResourceGroup: ${{ parameters.azureresourcegroup }}
                kubernetesCluster: ${{ parameters.kubernetescluster }}
                namespace: ${{ parameters.kubernetesnamespace }}
                releaseName: ${{ parameters.releasename }}
                command: upgrade
                chartName: ${{ parameters.chartname }}
                valueFile: ${{ parameters.valueFile }}
                chartType: Name
                install: true