jobs:
  - job: Prepare_environment
    displayName: Prepare environment
    pool:
      name: default
    steps:
      - task: Bash@3
        displayName: Prepare environment variable
        inputs:
          targetType: inline
          script: |
            commitID=$(Build.SourceVersion)
            echo "##vso[task.setvariable variable=crm.shortcommit;isOutput=true]${commitID:0:7}"
            echo "##vso[task.setvariable variable=crm.helmversion;isOutput=true]2.14.3"
            echo "##vso[task.setvariable variable=crm.kubectlversion;isOutput=true]1.12.8"
        name: setGlobalVarStep
      - task: Bash@3
        displayName: Print environment variables
        inputs:
          targetType: inline
          script: |
            echo $(setGlobalVarStep.crm.shortcommit)