jobs:
  - job: Prepare_environment
    displayName: Prepare environment
    pool:
      name: default
    steps:
      - task: Bash@3
        displayName: Prepare environment variable
        inputs:
          targetType: inline
          script: |
            commitID=$(Build.SourceVersion)
            echo "##vso[task.setvariable variable=CRM.ShortCommit;isOutput=true]${commitID:0:6}"
        name: setGlobalVarStep
      - task: Bash@3
        displayName: Prepare environment variable
        inputs:
          targetType: inline
          script: |
            echo $(setGlobalVarStep.CRM.ShortCommit)