parameters:
  services: ''
  registryendpoint: '' 

jobs:
  - job: Publish_Docker_Images
    displayName: Publish images
    variables:
      crm.shortcommit: $[dependencies.Prepare_environment.outputs['setGlobalVarStep.crm.shortcommit']]
    dependsOn: 
    - Prepare_environment
    pool:
      name: default
    steps:
      - task: DockerCompose@0
        displayName: Compose push ${{ parameters.services }}
        inputs:
          dockerComposeCommand: 'push ${{ parameters.services }}'
          containerregistrytype: Container Registry
          dockerRegistryEndpoint: ${{ parameters.registryendpoint }}
          dockerComposeFile: docker-compose.yml
          qualifyImageNames: true
          projectName: ""
          dockerComposeFileArgs: |
            TAG=$(crm.shortcommit)