parameters:
  service: ''
  azuresubscription: ''
  azureresourcegroup: ''
  kubernetescluster: ''

jobs:
  - job: Publish_Helm_Chart
    displayName: Publish helm chart
    variables:
      shortcommit: $[dependencies.Prepare_environment.outputs['setGlobalVarStep.shortcommit']]
      helmversion: $[dependencies.Prepare_environment.outputs['setGlobalVarStep.helmversion']]
      kubectlversion: $[dependencies.Prepare_environment.outputs['setGlobalVarStep.kubectlversion']]
    dependsOn: 
    - Prepare_environment
    pool:
      name: default
    steps:
      - task: HelmInstaller@0
        displayName: Helm installer
        inputs:
          helmVersion: $(helmversion)
          kubectlVersion: $(kubectlversion)
          checkLatestKubectl: false
          
      - task: HelmDeploy@0
        displayName: Helm version
        inputs:
          azureSubscription: $(azuresubscription)
          azureResourceGroup: $(azureresourcegroup)
          kubernetesCluster: $(kubernetescluster)
          command: version

      - task: HelmDeploy@0
        displayName: Helm package
        inputs:
          azureSubscription: $(azuresubscription)
          azureResourceGroup: $(azureresourcegroup)
          kubernetesCluster: $(kubernetescluster)
          command: package
          chartPath: k8s/charts/${{ parameters.service }}
          destination: $(Build.ArtifactStagingDirectory)
          arguments: --app-version $(Build.BuildNumber) --version $(Build.BuildNumber)

      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: $(Build.ArtifactStagingDirectory)/${{ parameters.service }}-$(Build.BuildNumber).tgz
          artifactName: helm