parameters:
  services: ''
  registryEndpoint: ''

jobs:
  - job: Publish_Docker_Images
    displayName: Publish images
    variables:
      CRM.ShortCommit: $[dependencies.Prepare_environment.outputs['setGlobalVarStep.CRM.ShortCommit']]
    dependsOn: 
    - Prepare_environment
    - Build_service
    - Run_Integration_Tests
    condition: and(succeeded(), eq(variables['CRM.NightlyBuild'], 'true'))
    pool:
      name: default
    steps:
      - task: DockerCompose@0
        displayName: Compose push ${{ parameters.services }}
        inputs:
          dockerComposeCommand: 'push ${{ parameters.services }}'
          containerregistrytype: Container Registry
          dockerRegistryEndpoint: ${{ parameters.registryEndpoint }}
          dockerComposeFile: docker-compose.yml
          qualifyImageNames: true
          projectName: ""
          dockerComposeFileArgs: |
            TAG=$(CRM.ShortCommit)