# Default values for contact-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: crmnow/contact-api
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "contact-api"

service:
  type: ClusterIP
  port: 5001
  grpcPort: 15001

ingress:
  enabled: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

env:
  values:
    - name: rabbitMQ__Url
      value: rabbitmq://rabbitmq
    - name: ConnectionStrings__contact
      value: Server=postgresql;Port=5432;Database=crm-contact;User Id=lab;Password=P@ssw0rd;
    - name: OpenTelemetry_Enabled
      value: false
    - name: Logging__Seq__Url
      value: http://seq.monitoring.svc.cluster.local
    - name: Logging__Seq__ApiKey
      value: 11zWlcFxJYXUFqKXoKGK
