---
- name: Create Network Security Group that allows SSH
  azure_rm_securitygroup:
    resource_group: "{{ azure.resource_group }}"
    name: "sg-{{ vm_name }}"
    rules:
      - name: SSH
        protocol: Tcp
        destination_port_range: 22
        access: Allow
        priority: 1001
        direction: Inbound
      - name: DockerContainer
        protocol: Tcp
        destination_port_range: 32768-33000
        access: Allow
        priority: 1002
        direction: Inbound
  tags:
        - vm

- name: Create a public ip address
  azure_rm_publicipaddress:
    resource_group: "{{ azure.resource_group }}"
    name: "pip-{{ vm_name }}"
    domain_name_label: "{{ vm_name }}"
  when: 
    - azure.enable_public_ip == true
  tags:
        - vm

- name: Create virtual network inteface card
  azure_rm_networkinterface:
    resource_group: "{{ azure.resource_group }}"
    name: "nic-{{ vm_name }}"
    virtual_network: "lab-vpn"
    subnet: "{{ subnet_name }}"
    security_group: "sg-{{ vm_name }}"
    ip_configurations:
      - name: ipconfig1
        primary: true
        public_ip_address_name: "{{ 'pip-' + vm_name if (azure.enable_public_ip == true) else  '' }}"
  tags:
        - vm

- name: Create VM
  azure_rm_virtualmachine:
    resource_group: "{{ azure.resource_group }}"
    name: "{{ vm_name }}"
    vm_size: "{{ vm_size }}"
    admin_username: "{{ admin.username }}"
    ssh_password_enabled: false
    ssh_public_keys:
      - path: "/home/{{ admin.username }}/.ssh/authorized_keys"
        key_data: "{{ ssh_key }}"
    network_interfaces: "nic-{{ vm_name }}"
    image:
      offer: "UbuntuServer"
      publisher: "Canonical"
      sku: "18.04-LTS"
      version: "latest"
  tags:
        - vm