variables:
    CRM.RegistryEndpoint: crm-registry
    disable.coverage.autogenerate: 'true'

trigger:
  branches:
    include:
      - master
      - feature/*
    exclude:
      - ref/tags/*
  paths:
    include:
      - src/Lead/CRM.Lead.Api
      - src/Lead/CRM.Lead.FunctionalTests
      - src/BuildingBlocks/CRM.DataContract
      - src/BuildingBlocks/CRM.Shared
jobs:
  - template: ../prepare-env.yml
  
  - template: ../build-services.yml
    parameters:
      services: communication-api

  - template: ../run-integration-test.yml
    parameters:
      testService: communication-api-test

  - template: ../publish-docker-images.yml
    parameters:
      services: communication-api
      registryEndpoint: $(CRM.RegistryEndpoint)