- name: Create resouce group
  azure_rm_resourcegroup:
    name: "{{ azure.resource_group }}"
    location: "{{ azure.location }}"
  tags:
    - network

- name: Create virtual network
  azure_rm_virtualnetwork:
    resource_group: "{{ azure.resource_group }}"
    name: "{{ azure.virtual_network_name }}"
    address_prefixes_cidr: 
      - 172.10.0.0/16
  tags:
    - network
    
- name: Add subnet
  azure_rm_subnet:
    resource_group: "{{ azure.resource_group }}"
    name: "{{ subnet_name }}"
    address_prefix: "{{ subnet_address_prefix }}"
    virtual_network: "{{ azure.virtual_network_name }}"
  tags:
    - network