variables:
    azuresubscription: AKS-lab-01
    azureresourcegroup: lab
    kubernetescluster: aks-lab-01

stages:

- stage: Deploy_Dev_Env
  displayName: Deploy external services for dev env
  jobs:
    - template: ../prepare-env.yml

    - template: ../install-helm-chart-by-name.yml
      parameters:
        name: Install_Nats
        chartname: stable/nats
        releasename: nats
        kubernetesnamespace: dev
        azuresubscription: $(azuresubscription)
        azureresourcegroup: $(azureresourcegroup)
        kubernetescluster: $(kubernetescluster)
        valueFile: $(Build.SourcesDirectory)/k8s/charts/nats/values.dev.yaml
    
    - template: ../install-helm-chart-by-name.yml
      parameters:
        name: Install_Postgresql
        chartname: stable/postgresql
        releasename: postgresql
        kubernetesnamespace: dev
        azuresubscription: $(azuresubscription)
        azureresourcegroup: $(azureresourcegroup)
        kubernetescluster: $(kubernetescluster)
        valueFile: $(Build.SourcesDirectory)/k8s/charts/postgresql/values.dev.yaml